spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        vote-channel-out:
          destination: vote.channel
          contentType: application/json