spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: generalBroker:9092
      bindings:
        vote-channel-out:
          destination: vote-channel
          contentType: application/json



simulator:
  thread:
    settings:
      minimum-number-of-thread: 1
      maximum-number-of-thread: 10