spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: generalBroker:9092
      bindings:
        vote-channel-out:
          destination: vote-channel
          contentType: application/json
          producer:
            partition-key-expression: headers['partitionKey']
            partition-count: 5



simulator:
  thread:
    settings:
      minimum-number-of-thread: 1
      maximum-number-of-thread: 10